[27/Dec/2018 14:15:32] "GET /admin/ HTTP/1.1" 302 0
[27/Dec/2018 14:15:32] "GET /admin/ HTTP/1.1" 302 0
[27/Dec/2018 14:15:33] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1660
[27/Dec/2018 14:15:33] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1660
[27/Dec/2018 14:15:35] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[27/Dec/2018 14:15:35] "GET /admin/ HTTP/1.1" 200 7366
[27/Dec/2018 14:15:35] "GET /static/admin/css/base.css HTTP/1.1" 200 16066
[27/Dec/2018 14:15:50] "GET /admin/ HTTP/1.1" 200 7366
[27/Dec/2018 14:15:53] "GET /admin/ HTTP/1.1" 302 0
[27/Dec/2018 14:15:53] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1660
[27/Dec/2018 14:15:53] "GET /static/admin/css/login.css HTTP/1.1" 200 1203
[27/Dec/2018 14:16:01] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[27/Dec/2018 14:16:01] "GET /admin/ HTTP/1.1" 200 7366
[27/Dec/2018 14:17:04] "GET /admin/ HTTP/1.1" 200 7366
[27/Dec/2018 14:17:17] "GET /admin/ HTTP/1.1" 200 7366
[27/Dec/2018 14:17:20] "GET /admin/lab/sample/ HTTP/1.1" 200 62885
[27/Dec/2018 14:17:20] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[27/Dec/2018 14:17:41] "POST /admin/lab/sample/ HTTP/1.1" 200 4622
[27/Dec/2018 14:17:42] "POST /admin/lab/sample/ HTTP/1.1" 302 0
[27/Dec/2018 14:17:43] "GET /admin/lab/sample/ HTTP/1.1" 200 62866
[27/Dec/2018 14:17:43] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[27/Dec/2018 14:18:11] "GET /admin/ HTTP/1.1" 302 0
[27/Dec/2018 14:18:11] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1660
[27/Dec/2018 14:18:12] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[27/Dec/2018 14:18:12] "GET /admin/ HTTP/1.1" 200 6844
[27/Dec/2018 14:18:12] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
[27/Dec/2018 14:18:14] "GET /admin/lab/sample/ HTTP/1.1" 200 62744
[27/Dec/2018 14:18:14] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[27/Dec/2018 14:18:40] "GET /admin/lab/ HTTP/1.1" 200 2576
[27/Dec/2018 14:18:42] "GET /admin/ HTTP/1.1" 200 6844
[27/Dec/2018 14:18:43] "GET /admin/paper/paper/ HTTP/1.1" 200 5928
[27/Dec/2018 14:18:43] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[27/Dec/2018 14:18:44] "GET /admin/paper/paper/1/change/ HTTP/1.1" 200 7925
[27/Dec/2018 14:18:44] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[27/Dec/2018 14:18:51] "GET /media/SGRNJ/Database/test/1.11/lab_project/media/paper/pdf/2017_celRep_glio.pdf HTTP/1.1" 200 3860545
[27/Dec/2018 14:18:53] "GET /admin/paper/paper/1/change/ HTTP/1.1" 200 7925
[29/Dec/2018 09:23:03] "GET /admin/ HTTP/1.1" 302 0
[29/Dec/2018 09:23:05] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1660
[29/Dec/2018 09:23:05] "GET /static/admin/css/base.css HTTP/1.1" 200 16066
[29/Dec/2018 09:23:05] "GET /static/admin/css/login.css HTTP/1.1" 200 1203
[29/Dec/2018 09:23:05] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
Not Found: /favicon.ico
[29/Dec/2018 09:23:05] "GET /favicon.ico HTTP/1.1" 404 2197
[29/Dec/2018 09:23:05] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
[29/Dec/2018 09:23:05] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
[29/Dec/2018 09:23:10] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[29/Dec/2018 09:23:10] "GET /admin/ HTTP/1.1" 200 6844
[29/Dec/2018 09:23:10] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
[29/Dec/2018 09:23:10] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
[29/Dec/2018 09:23:10] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
[29/Dec/2018 09:23:10] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[29/Dec/2018 09:23:10] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[29/Dec/2018 09:23:13] "GET /admin/lab/sample/ HTTP/1.1" 200 62744
[29/Dec/2018 09:23:13] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6170
[29/Dec/2018 09:23:13] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:23:13] "GET /static/admin/js/core.js HTTP/1.1" 200 7976
[29/Dec/2018 09:23:13] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 258648
[29/Dec/2018 09:23:13] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
[29/Dec/2018 09:23:13] "GET /static/admin/js/urlify.js HTTP/1.1" 200 8186
[29/Dec/2018 09:23:13] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1538
[29/Dec/2018 09:23:13] "GET /static/admin/js/actions.js HTTP/1.1" 200 6501
[29/Dec/2018 09:23:13] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6591
[29/Dec/2018 09:23:13] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 128820
[29/Dec/2018 09:23:13] "GET /static/admin/img/search.svg HTTP/1.1" 200 458
[29/Dec/2018 09:23:14] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[29/Dec/2018 09:30:43] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 09:30:45] "GET /admin/lab/project/ HTTP/1.1" 200 25340
[29/Dec/2018 09:30:45] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:30:54] "GET /admin/lab/project/33/change/ HTTP/1.1" 200 9773
[29/Dec/2018 09:30:54] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:30:54] "GET /static/admin/css/forms.css HTTP/1.1" 200 8173
[29/Dec/2018 09:30:54] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 20529
[29/Dec/2018 09:30:54] "GET /static/admin/js/change_form.js HTTP/1.1" 200 712
[29/Dec/2018 09:30:54] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495
[29/Dec/2018 09:30:54] "GET /static/admin/css/widgets.css HTTP/1.1" 200 10340
[29/Dec/2018 09:30:54] "GET /static/admin/js/calendar.js HTTP/1.1" 200 7790
[29/Dec/2018 09:30:54] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[29/Dec/2018 09:31:34] "GET /admin/lab/project/ HTTP/1.1" 302 0
[29/Dec/2018 09:31:34] "GET /admin/login/?next=/admin/lab/project/ HTTP/1.1" 200 1684
[29/Dec/2018 09:31:37] "GET /admin/lab/project/33/change/ HTTP/1.1" 302 0
[29/Dec/2018 09:31:37] "GET /admin/login/?next=/admin/lab/project/33/change/ HTTP/1.1" 200 1704
[29/Dec/2018 09:31:40] "POST /admin/login/?next=/admin/lab/project/33/change/ HTTP/1.1" 302 0
[29/Dec/2018 09:31:41] "GET /admin/lab/project/33/change/ HTTP/1.1" 200 9773
[29/Dec/2018 09:31:41] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:31:43] "GET /admin/lab/project/ HTTP/1.1" 200 25340
[29/Dec/2018 09:31:43] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:32:14] "GET /admin/lab/project/33/change/ HTTP/1.1" 200 9773
[29/Dec/2018 09:32:14] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:32:26] "GET /admin/lab/project/ HTTP/1.1" 200 25340
[29/Dec/2018 09:39:26] "GET /admin/lab/project/?o=2 HTTP/1.1" 200 26557
[29/Dec/2018 09:39:26] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:39:26] "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
[29/Dec/2018 09:39:50] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/RD2018020.report.html HTTP/1.1" 200 4592328
[29/Dec/2018 09:39:50] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/0.QC/KTT_T_Region.svg HTTP/1.1" 200 76255
[29/Dec/2018 09:39:50] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/0.QC/KTT_T_UMIcounts.svg HTTP/1.1" 200 149533
[29/Dec/2018 09:39:50] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/0.QC/FastQC_KTT_T.clean.png HTTP/1.1" 200 105916
[29/Dec/2018 09:39:50] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/0.QC/FastQC_KTT_T.raw.png HTTP/1.1" 200 116300
[29/Dec/2018 09:39:50] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/0.QC/KTT_T.biotype_pct.svg HTTP/1.1" 200 128003
[29/Dec/2018 09:39:50] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/0.QC/KTT_T_downsampleMedianGenes.svg HTTP/1.1" 200 70603
[29/Dec/2018 09:39:50] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/0.QC/KTT_T_downsampleSaturation.svg HTTP/1.1" 200 69094
[29/Dec/2018 09:39:50] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/1.QC_mito/KTT_T.Mitopercent.png HTTP/1.1" 200 27150
[29/Dec/2018 09:39:50] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/2.Cluster/KTT_T.corrplot.png HTTP/1.1" 200 18332
[29/Dec/2018 09:39:50] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/1.QC_mito/KTT_T.QC_tsneFeatureplot.svg HTTP/1.1" 200 790770
[29/Dec/2018 09:39:50] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/2.Cluster/KTT_T.PercentPerCell.png HTTP/1.1" 200 16557
[29/Dec/2018 09:39:50] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/1.QC_mito/KTT_T.QC_umapFeatureplot.svg HTTP/1.1" 200 793974
[29/Dec/2018 09:39:50] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/3.RD/KTT_T.PCA.png HTTP/1.1" 200 41753
[29/Dec/2018 09:39:50] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/3.RD/KTT_T.PCElbowPlot.png HTTP/1.1" 200 11134
[29/Dec/2018 09:39:50] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/3.RD/KTT_T.tsne.png HTTP/1.1" 200 56694
[29/Dec/2018 09:39:50] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/3.RD/KTT_T.umap.png HTTP/1.1" 200 35651
[29/Dec/2018 09:39:51] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/7.monocle/KTT_T.Pseudotime_cluster.png HTTP/1.1" 200 21622
[29/Dec/2018 09:39:51] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/7.monocle/KTT_T.trajectories_cluster.png HTTP/1.1" 200 20755
[29/Dec/2018 09:39:51] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/5.Marker_Gene/KTT_T.markergene_DOHeatmapplot.png HTTP/1.1" 200 19537
[29/Dec/2018 09:39:51] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/5.Marker_Gene/KTT_T.cluster_Heatmapplot.png HTTP/1.1" 200 11020
[29/Dec/2018 09:39:51] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/5.Marker_Gene/KTT_T.markergene_Dotplot.png HTTP/1.1" 200 22237
[29/Dec/2018 09:39:51] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/5.Marker_Gene/KTT_T.markergene_vlnplot1.png HTTP/1.1" 200 34741
[29/Dec/2018 09:39:51] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/5.Marker_Gene/KTT_T.top10markergene_DOHeatmapplot.png HTTP/1.1" 200 55895
[29/Dec/2018 09:39:51] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/5.Marker_Gene/KTT_T.markergene_umapFeatureplot1.png HTTP/1.1" 200 47156
[29/Dec/2018 09:39:51] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/5.Marker_Gene/KTT_T.markergene_tsneFeatureplot1.png HTTP/1.1" 200 73080
[29/Dec/2018 09:39:51] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/6.enrich/KTT_T_cluster1_KEGGbar.svg HTTP/1.1" 200 153220
[29/Dec/2018 09:39:51] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/6.enrich/KTT_T_cluster1_GObar.svg HTTP/1.1" 200 198876
[29/Dec/2018 09:39:51] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/6.enrich/KTT_T_cluster1_Reactomebar.svg HTTP/1.1" 200 165829
[29/Dec/2018 09:39:51] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/6.enrich/KTT_T_cluster1_GOdot.svg HTTP/1.1" 200 197840
[29/Dec/2018 09:39:51] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/6.enrich/KTT_T_cluster1_Reactomedot.svg HTTP/1.1" 200 181439
[29/Dec/2018 09:39:51] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/6.enrich/KTT_T_cluster1_KEGGdot.svg HTTP/1.1" 200 160672
[29/Dec/2018 09:39:51] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/6.enrich/mmu00190_pathway.png HTTP/1.1" 200 105816
[29/Dec/2018 09:39:53] "GET /media/SGRNJ/RandD/RD2018020/RD2018020_report/src/2.Cluster/KTT_T.Hcluster.svg HTTP/1.1" 200 3477850
[29/Dec/2018 09:39:54] "GET /admin/lab/project/?o=2 HTTP/1.1" 200 26557
[29/Dec/2018 09:39:55] "GET /admin/lab/project/ HTTP/1.1" 200 25340
[29/Dec/2018 09:40:12] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 09:40:13] "GET /admin/lab/sample/ HTTP/1.1" 200 62744
[29/Dec/2018 09:40:13] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:40:19] "GET /admin/lab/sample/336/change/ HTTP/1.1" 200 11640
[29/Dec/2018 09:40:19] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:40:21] "GET /admin/lab/sample/ HTTP/1.1" 200 62744
[29/Dec/2018 09:41:12] "GET / HTTP/1.1" 200 52
[29/Dec/2018 09:41:14] "GET /admin/lab/sample/ HTTP/1.1" 200 62744
[29/Dec/2018 09:41:55] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 09:41:57] "GET /admin/lab/project/ HTTP/1.1" 200 25340
[29/Dec/2018 09:41:57] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:42:10] "GET /admin/lab/project/32/change/ HTTP/1.1" 200 9696
[29/Dec/2018 09:42:10] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:42:19] "POST /admin/lab/project/32/change/ HTTP/1.1" 302 0
[29/Dec/2018 09:42:20] "GET /admin/lab/project/ HTTP/1.1" 200 25562
[29/Dec/2018 09:42:20] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:42:20] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[29/Dec/2018 09:42:23] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 09:42:25] "GET /admin/lab/sample/ HTTP/1.1" 200 62756
[29/Dec/2018 09:42:25] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:42:33] "GET /admin/lab/sample/?project__id__exact=33 HTTP/1.1" 200 63376
[29/Dec/2018 09:42:33] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:42:35] "GET /admin/lab/sample/?project__id__exact=32 HTTP/1.1" 200 14361
[29/Dec/2018 09:42:35] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:42:46] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 09:42:48] "GET /admin/lab/project/ HTTP/1.1" 200 25342
[29/Dec/2018 09:42:48] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:43:10] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 09:43:12] "GET /admin/lab/sample/ HTTP/1.1" 200 62756
[29/Dec/2018 09:43:12] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:43:13] "GET /admin/lab/sample/add/ HTTP/1.1" 200 11394
[29/Dec/2018 09:43:13] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:43:16] "GET /admin/lab/project/add/?_to_field=id&_popup=1 HTTP/1.1" 200 8360
[29/Dec/2018 09:43:16] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:43:35] "GET /admin/lab/sample/ HTTP/1.1" 200 62756
[29/Dec/2018 09:45:20] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 09:45:21] "GET /admin/lab/project/ HTTP/1.1" 200 25342
[29/Dec/2018 09:45:21] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:47:50] "GET /admin/lab/ HTTP/1.1" 302 0
[29/Dec/2018 09:47:50] "GET /admin/login/?next=/admin/lab/ HTTP/1.1" 200 1668
[29/Dec/2018 09:47:52] "POST /admin/login/?next=/admin/lab/ HTTP/1.1" 302 0
[29/Dec/2018 09:47:52] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 09:47:53] "GET /admin/lab/sample/ HTTP/1.1" 200 62756
[29/Dec/2018 09:47:53] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 09:59:38] "GET /admin/lab/sample/ HTTP/1.1" 200 62756
[29/Dec/2018 09:59:38] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
Performing system checks...

System check identified no issues (0 silenced).
December 27, 2018 - 14:15:14
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
[29/Dec/2018 10:00:23] "GET /admin/lab/sample/ HTTP/1.1" 200 61353
[29/Dec/2018 10:00:23] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:00:31] "GET /admin/lab/sample/ HTTP/1.1" 200 61353
[29/Dec/2018 10:00:31] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 10:00:15
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
Internal Server Error: /admin/lab/sample/
Traceback (most recent call last):
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1542, in changelist_view
    self.list_max_show_all, self.list_editable, self,
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 78, in __init__
    self.queryset = self.get_queryset(request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 317, in get_queryset
    filters_use_distinct) = self.get_filters(request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 132, in get_filters
    self.model, self.model_admin, field_path=field_path
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/filters.py", line 165, in __init__
    other_model = get_model_from_relation(field)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 453, in get_model_from_relation
    raise NotRelationField
NotRelationField
[29/Dec/2018 10:01:52] "GET /admin/lab/sample/ HTTP/1.1" 500 127098
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 10:01:44
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
[29/Dec/2018 10:02:31] "GET /admin/lab/sample/ HTTP/1.1" 200 62756
[29/Dec/2018 10:02:31] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:02:49] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 10:02:50] "GET /admin/lab/project/ HTTP/1.1" 200 25342
[29/Dec/2018 10:02:50] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:03:04] "GET /admin/lab/project/?o=2 HTTP/1.1" 200 26559
[29/Dec/2018 10:03:04] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:03:43] "GET /admin/lab/project/22/change/?_changelist_filters=o%3D2 HTTP/1.1" 200 9768
[29/Dec/2018 10:03:43] "GET /admin/lab/project/22/change/?_changelist_filters=o%3D2 HTTP/1.1" 200 9768
[29/Dec/2018 10:03:43] "GET /admin/lab/project/?o=3.2 HTTP/1.1" 200 26997
[29/Dec/2018 10:03:43] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:03:45] "GET /admin/lab/project/?o=-3.2 HTTP/1.1" 200 27039
[29/Dec/2018 10:03:45] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 10:02:30
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function wrapper at 0x7f1c1e99f1b8>
Traceback (most recent call last):
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/SGRNJ/Database/develop/lab/lab/models.py", line 32
    p_id+")" = models.CharField(max_length=30,blank=True)
SyntaxError: can't assign to operator
[29/Dec/2018 10:05:07] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 10:05:09] "GET /admin/lab/sample/ HTTP/1.1" 200 63130
[29/Dec/2018 10:05:09] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:05:14] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 10:05:15] "GET /admin/lab/sample/ HTTP/1.1" 200 63130
[29/Dec/2018 10:05:15] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:05:16] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 10:05:17] "GET /admin/lab/project/ HTTP/1.1" 200 25342
[29/Dec/2018 10:05:17] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:05:23] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 10:05:24] "GET /admin/lab/sample/ HTTP/1.1" 200 63130
[29/Dec/2018 10:05:24] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:05:58] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 10:05:59] "GET /admin/lab/sample/ HTTP/1.1" 200 63130
[29/Dec/2018 10:05:59] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:06:04] "GET /admin/lab/sample/add/ HTTP/1.1" 200 11768
[29/Dec/2018 10:06:04] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:06:24] "GET /admin/lab/sample/ HTTP/1.1" 200 63130
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 10:05:03
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
[29/Dec/2018 10:07:16] "GET /admin/lab/sample/ HTTP/1.1" 200 63931
[29/Dec/2018 10:07:16] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:07:54] "GET /admin/lab/sample/?q=huamn HTTP/1.1" 200 10888
[29/Dec/2018 10:07:54] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:07:58] "GET /admin/lab/sample/?q=human HTTP/1.1" 200 10888
[29/Dec/2018 10:07:59] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:08:00] "GET /admin/lab/sample/?q=human HTTP/1.1" 200 10888
[29/Dec/2018 10:08:00] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:08:04] "GET /admin/lab/sample/?q= HTTP/1.1" 200 66825
[2018-12-29 10:08:04,171] - Broken pipe from ('192.168.1.3', 57401)

[29/Dec/2018 10:08:05] "GET /admin/lab/sample/?q= HTTP/1.1" 200 66825
[29/Dec/2018 10:08:05] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:08:12] "GET /admin/lab/sample/?q=sample HTTP/1.1" 200 14156
[29/Dec/2018 10:08:12] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 10:07:15
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function wrapper at 0x7f3c347365f0>
Traceback (most recent call last):
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/SGRNJ/Database/develop/lab/lab/admin.py", line 61, in <module>
    class SampleAdmin(admin.ModelAdmin):
  File "/SGRNJ/Database/develop/lab/lab/admin.py", line 83, in SampleAdmin
    ('sample_date'),
TypeError: 'tuple' object is not callable
[29/Dec/2018 10:09:45] "GET /admin/lab/sample/?q=sample HTTP/1.1" 200 14156
[29/Dec/2018 10:09:45] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:09:53] "GET /admin/lab/sample/?q=human HTTP/1.1" 200 67646
[29/Dec/2018 10:09:53] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:10:00] "GET /admin/lab/sample/?q=P2018003 HTTP/1.1" 200 15368
[29/Dec/2018 10:10:00] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:10:32] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 10:10:34] "GET /admin/lab/sample/ HTTP/1.1" 200 63931
[29/Dec/2018 10:10:34] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:10:39] "GET /admin/lab/sample/?q=%E9%AB%98%E6%9C%88 HTTP/1.1" 200 11512
[29/Dec/2018 10:10:39] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 10:09:28
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 10:10:58
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 10:11:08
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
Internal Server Error: /admin/lab/sample/
Traceback (most recent call last):
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1542, in changelist_view
    self.list_max_show_all, self.list_editable, self,
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 78, in __init__
    self.queryset = self.get_queryset(request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 351, in get_queryset
    qs, search_use_distinct = self.model_admin.get_search_results(request, qs, self.query)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/options.py", line 910, in get_search_results
    queryset = queryset.filter(reduce(operator.or_, or_queries))
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1270, in _add_q
    current_negated, allow_joins, split_subq)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1201, in build_filter
    raise FieldError('Related Field got invalid lookup: {}'.format(lookups[0]))
FieldError: Related Field got invalid lookup: icontains
[29/Dec/2018 10:13:22] "GET /admin/lab/sample/?q=%E9%AB%98%E6%9C%88 HTTP/1.1" 500 163085
Internal Server Error: /admin/lab/sample/
Traceback (most recent call last):
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1542, in changelist_view
    self.list_max_show_all, self.list_editable, self,
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 78, in __init__
    self.queryset = self.get_queryset(request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 351, in get_queryset
    qs, search_use_distinct = self.model_admin.get_search_results(request, qs, self.query)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/options.py", line 910, in get_search_results
    queryset = queryset.filter(reduce(operator.or_, or_queries))
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1270, in _add_q
    current_negated, allow_joins, split_subq)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1201, in build_filter
    raise FieldError('Related Field got invalid lookup: {}'.format(lookups[0]))
FieldError: Related Field got invalid lookup: icontains
[29/Dec/2018 10:14:28] "GET /admin/lab/sample/?q=%E9%AB%98%E6%9C%88 HTTP/1.1" 500 163085
[29/Dec/2018 10:14:29] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 10:14:30] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 10:14:31] "GET /admin/lab/sample/ HTTP/1.1" 200 63931
[29/Dec/2018 10:14:31] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
Internal Server Error: /admin/lab/sample/
Traceback (most recent call last):
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1542, in changelist_view
    self.list_max_show_all, self.list_editable, self,
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 78, in __init__
    self.queryset = self.get_queryset(request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 351, in get_queryset
    qs, search_use_distinct = self.model_admin.get_search_results(request, qs, self.query)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/options.py", line 910, in get_search_results
    queryset = queryset.filter(reduce(operator.or_, or_queries))
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1270, in _add_q
    current_negated, allow_joins, split_subq)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1201, in build_filter
    raise FieldError('Related Field got invalid lookup: {}'.format(lookups[0]))
FieldError: Related Field got invalid lookup: icontains
[29/Dec/2018 10:14:36] "GET /admin/lab/sample/?q=%E9%AB%98%E6%9C%88 HTTP/1.1" 500 162950
[29/Dec/2018 10:14:40] "GET /admin/lab/sample/ HTTP/1.1" 200 63931
[29/Dec/2018 10:14:53] "GET /admin/lab/sample/add/ HTTP/1.1" 200 11768
[29/Dec/2018 10:14:53] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 10:13:22
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
[29/Dec/2018 10:15:35] "GET /admin/lab/sample/add/ HTTP/1.1" 200 11873
[29/Dec/2018 10:15:35] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:15:49] "GET /admin/lab/sample/ HTTP/1.1" 200 64036
[29/Dec/2018 10:15:49] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 10:15:34
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
[29/Dec/2018 10:16:04] "GET /admin/lab/sample/ HTTP/1.1" 200 64036
[29/Dec/2018 10:16:04] "GET /admin/lab/sample/ HTTP/1.1" 200 64036
[29/Dec/2018 10:16:04] "GET /admin/lab/sample/ HTTP/1.1" 200 64036
[29/Dec/2018 10:16:04] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:16:07] "GET /admin/lab/sample/?q=%E9%AB%98%E6%9C%88 HTTP/1.1" 200 11617
[29/Dec/2018 10:16:08] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 10:16:02
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function wrapper at 0x7ff05a1bd5f0>
Traceback (most recent call last):
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/SGRNJ/Database/develop/lab/lab/admin.py", line 61, in <module>
    class SampleAdmin(admin.ModelAdmin):
  File "/SGRNJ/Database/develop/lab/lab/admin.py", line 84, in SampleAdmin
    search_fields = ['name','sample_date','library_id','description','species','project__p_id','library_type',created_by__last_name]
NameError: name 'created_by__last_name' is not defined
[29/Dec/2018 10:18:08] "GET /admin/lab/sample/?q=%E9%AB%98%E6%9C%88 HTTP/1.1" 200 14981
[29/Dec/2018 10:18:08] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:18:14] "GET /admin/lab/sample/?q=%E9%AB%98%E6%9C%88 HTTP/1.1" 200 14981
[29/Dec/2018 10:18:14] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:18:24] "GET /admin/lab/sample/?q=%E9%AB%98%E6%9C%88 HTTP/1.1" 200 14981
[29/Dec/2018 10:18:25] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:18:26] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 10:18:28] "GET /admin/lab/sample/ HTTP/1.1" 200 64036
[29/Dec/2018 10:18:28] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:18:45] "GET /admin/lab/sample/?q=P2018003 HTTP/1.1" 200 15473
[29/Dec/2018 10:18:45] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:18:54] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 10:18:56] "GET /admin/lab/project/ HTTP/1.1" 200 25342
[29/Dec/2018 10:18:56] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 10:18:59] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 10:19:00] "GET /admin/lab/sample/ HTTP/1.1" 200 64036
[29/Dec/2018 10:19:00] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
Unhandled exception in thread started by <function wrapper at 0x7fedde727140>
Performing system checks...

Traceback (most recent call last):
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/SGRNJ/Database/develop/lab/lab_project/urls.py", line 19, in <module>
    from lab.views import *
  File "/SGRNJ/Database/develop/lab/lab/views.py", line 19
    
                             ^
IndentationError: expected an indented block
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 11:29:56
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
[29/Dec/2018 11:30:10] "GET /admin/ HTTP/1.1" 302 0
[29/Dec/2018 11:30:11] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1660
[29/Dec/2018 11:30:14] "GET / HTTP/1.1" 200 4015
[29/Dec/2018 11:37:54] "GET / HTTP/1.1" 200 4015
[29/Dec/2018 11:37:55] "GET / HTTP/1.1" 200 4015
[29/Dec/2018 11:37:56] "GET / HTTP/1.1" 200 4015
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 11:30:09
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
Not Found: /
[29/Dec/2018 11:38:04] "GET / HTTP/1.1" 404 2044
Not Found: /lab
[29/Dec/2018 11:38:10] "GET /lab HTTP/1.1" 404 2071
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 11:38:04
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function wrapper at 0x7fd97de27140>
Performing system checks...

Traceback (most recent call last):
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/SGRNJ/Database/develop/lab/lab_project/urls.py", line 24, in <module>
    url(r'^lab/', include('lab.urls')),
NameError: name 'include' is not defined
Unhandled exception in thread started by <function wrapper at 0x7f9a811d8140>
Performing system checks...

Traceback (most recent call last):
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/SGRNJ/Database/develop/lab/lab_project/urls.py", line 24, in <module>
    url(r'^lab/', include('lab.urls')),
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/SGRNJ/Database/develop/lab/lab/urls.py", line 5, in <module>
    import settings
ImportError: No module named settings
[29/Dec/2018 11:40:26] "GET /lab HTTP/1.1" 301 0
[29/Dec/2018 11:40:27] "GET /lab/ HTTP/1.1" 200 4015
[29/Dec/2018 11:40:36] "GET /admin/ HTTP/1.1" 302 0
[29/Dec/2018 11:40:36] "GET /admin/ HTTP/1.1" 302 0
[29/Dec/2018 11:40:36] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1660
[29/Dec/2018 11:40:36] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1660
[29/Dec/2018 11:40:38] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[29/Dec/2018 11:40:38] "GET /admin/ HTTP/1.1" 200 6948
Not Found: /
[29/Dec/2018 11:40:39] "GET / HTTP/1.1" 404 2149
[29/Dec/2018 11:40:42] "GET /admin/ HTTP/1.1" 200 6948
[29/Dec/2018 11:41:32] "GET /admin/lab/sample/add/ HTTP/1.1" 200 11873
[29/Dec/2018 11:41:32] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 11:41:34] "GET /admin/ HTTP/1.1" 200 6948
Not Found: /
[29/Dec/2018 11:41:38] "GET / HTTP/1.1" 404 2149
[29/Dec/2018 11:41:40] "GET /admin/ HTTP/1.1" 200 6948
[29/Dec/2018 11:42:08] "GET /lab/ HTTP/1.1" 200 4015
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 11:40:26
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
Not Found: /lab/1
[29/Dec/2018 11:47:58] "GET /lab/1 HTTP/1.1" 404 2231
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 11:47:55
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
[29/Dec/2018 11:48:07] "GET /lab/1 HTTP/1.1" 301 0
[29/Dec/2018 11:48:07] "GET /lab/1/ HTTP/1.1" 200 1
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 11:48:06
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
[29/Dec/2018 11:48:55] "GET /lab/1/ HTTP/1.1" 200 0
[29/Dec/2018 11:48:57] "GET /lab/1/ HTTP/1.1" 200 0
[29/Dec/2018 11:48:58] "GET /lab/1/ HTTP/1.1" 200 0
[29/Dec/2018 11:49:00] "GET /lab/2 HTTP/1.1" 301 0
[29/Dec/2018 11:49:00] "GET /lab/2/ HTTP/1.1" 200 32
[29/Dec/2018 11:49:03] "GET /lab/3 HTTP/1.1" 301 0
[29/Dec/2018 11:49:03] "GET /lab/3/ HTTP/1.1" 200 109
[29/Dec/2018 11:49:11] "GET /lab/4 HTTP/1.1" 301 0
[29/Dec/2018 11:49:11] "GET /lab/4/ HTTP/1.1" 200 107
[29/Dec/2018 11:49:16] "GET /lab/5 HTTP/1.1" 301 0
[29/Dec/2018 11:49:16] "GET /lab/5/ HTTP/1.1" 200 324
[29/Dec/2018 11:49:19] "GET /lab/6 HTTP/1.1" 301 0
[29/Dec/2018 11:49:19] "GET /lab/6/ HTTP/1.1" 200 146
[29/Dec/2018 11:49:22] "GET /lab/7 HTTP/1.1" 301 0
[29/Dec/2018 11:49:22] "GET /lab/7/ HTTP/1.1" 200 114
[29/Dec/2018 11:49:26] "GET /lab/8 HTTP/1.1" 301 0
[29/Dec/2018 11:49:26] "GET /lab/8/ HTTP/1.1" 200 264
[29/Dec/2018 11:49:29] "GET /lab/22 HTTP/1.1" 301 0
[29/Dec/2018 11:49:29] "GET /lab/22/ HTTP/1.1" 200 0
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 11:48:54
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
[29/Dec/2018 12:59:35] "GET /lab/22/ HTTP/1.1" 200 9
[29/Dec/2018 12:59:38] "GET /lab/1/ HTTP/1.1" 200 9
[29/Dec/2018 12:59:41] "GET /lab/2/ HTTP/1.1" 200 1121
[29/Dec/2018 12:59:53] "GET /lab/2/ HTTP/1.1" 200 1121
[29/Dec/2018 12:59:54] "GET /lab/2/ HTTP/1.1" 200 849
[29/Dec/2018 13:01:27] "GET /lab/ HTTP/1.1" 200 4015
[29/Dec/2018 13:01:29] "GET /lab/ HTTP/1.1" 200 4015
[29/Dec/2018 13:01:32] "GET /lab/ HTTP/1.1" 200 4015
[29/Dec/2018 13:01:33] "GET /lab/ HTTP/1.1" 200 4015
[29/Dec/2018 13:01:33] "GET /lab/ HTTP/1.1" 200 4015
[29/Dec/2018 13:01:33] "GET /lab/ HTTP/1.1" 200 4015
[29/Dec/2018 13:01:33] "GET /lab/ HTTP/1.1" 200 4015
[29/Dec/2018 13:02:15] "GET /lab/ HTTP/1.1" 200 4671
[29/Dec/2018 13:02:17] "GET /lab/ HTTP/1.1" 200 4671
Not Found: /lab/lab/1
[29/Dec/2018 13:02:18] "GET /lab/lab/1 HTTP/1.1" 404 2448
Not Found: /lab/lab/1
[29/Dec/2018 13:02:25] "GET /lab/lab/1 HTTP/1.1" 404 2448
Not Found: /lab/lab/1
[29/Dec/2018 13:02:26] "GET /lab/lab/1 HTTP/1.1" 404 2448
Not Found: /lab/lab/1
[29/Dec/2018 13:02:28] "GET /lab/lab/1 HTTP/1.1" 404 2448
[29/Dec/2018 13:02:34] "GET /lab/ HTTP/1.1" 200 4531
[29/Dec/2018 13:02:35] "GET /lab/1/ HTTP/1.1" 200 9
[29/Dec/2018 13:02:38] "GET /lab/2/ HTTP/1.1" 200 849
[29/Dec/2018 13:02:49] "GET /lab/24 HTTP/1.1" 301 0
[29/Dec/2018 13:02:49] "GET /lab/24/ HTTP/1.1" 200 553
[29/Dec/2018 13:03:06] "GET /lab/34 HTTP/1.1" 301 0
[29/Dec/2018 13:03:06] "GET /lab/34/ HTTP/1.1" 200 2596
[29/Dec/2018 13:03:26] "GET /admin/ HTTP/1.1" 302 0
[29/Dec/2018 13:03:27] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1660
[29/Dec/2018 13:03:29] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[29/Dec/2018 13:03:29] "GET /admin/ HTTP/1.1" 200 6948
[29/Dec/2018 13:03:31] "GET /admin/lab/sample/ HTTP/1.1" 200 64036
[29/Dec/2018 13:03:31] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 13:03:34] "GET /admin/lab/sample/?project__id__exact=34 HTTP/1.1" 200 25549
[29/Dec/2018 13:03:34] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 13:03:38] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 13:03:40] "GET /admin/lab/project/ HTTP/1.1" 200 25342
[29/Dec/2018 13:03:40] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 13:07:53] "GET /lab/33 HTTP/1.1" 301 0
[29/Dec/2018 13:07:53] "GET /lab/33/ HTTP/1.1" 200 10071
[29/Dec/2018 13:15:34] "GET /lab/ HTTP/1.1" 200 4531
[29/Dec/2018 13:15:36] "GET /lab/16 HTTP/1.1" 301 0
[29/Dec/2018 13:15:36] "GET /lab/16/ HTTP/1.1" 200 129
[29/Dec/2018 13:15:40] "GET /lab/27 HTTP/1.1" 301 0
[29/Dec/2018 13:15:40] "GET /lab/27/ HTTP/1.1" 200 3000
[29/Dec/2018 13:15:55] "GET /lab/35 HTTP/1.1" 301 0
[29/Dec/2018 13:15:55] "GET /lab/35/ HTTP/1.1" 200 9
[29/Dec/2018 13:15:59] "GET /lab/34/ HTTP/1.1" 200 2596
[29/Dec/2018 13:16:06] "GET /lab/15 HTTP/1.1" 301 0
[29/Dec/2018 13:16:06] "GET /lab/15/ HTTP/1.1" 200 604
[29/Dec/2018 13:16:20] "GET /lab/29 HTTP/1.1" 301 0
[29/Dec/2018 13:16:20] "GET /lab/29/ HTTP/1.1" 200 699
[29/Dec/2018 13:16:26] "GET /lab/29/ HTTP/1.1" 200 699
[29/Dec/2018 13:16:40] "GET /lab/8/ HTTP/1.1" 200 1283
[29/Dec/2018 13:16:47] "GET /lab/9 HTTP/1.1" 301 0
[29/Dec/2018 13:16:47] "GET /lab/9/ HTTP/1.1" 200 819
[29/Dec/2018 13:17:27] "GET /lab/10 HTTP/1.1" 301 0
[29/Dec/2018 13:17:27] "GET /lab/10/ HTTP/1.1" 200 9
[29/Dec/2018 13:17:30] "GET /lab/19 HTTP/1.1" 301 0
[29/Dec/2018 13:17:30] "GET /lab/19/ HTTP/1.1" 200 9
[29/Dec/2018 13:17:37] "GET /lab/20 HTTP/1.1" 301 0
[29/Dec/2018 13:17:37] "GET /lab/20/ HTTP/1.1" 200 848
[29/Dec/2018 13:17:43] "GET /lab/8/ HTTP/1.1" 200 1283
[29/Dec/2018 13:17:46] "GET /lab/29/ HTTP/1.1" 200 699
[29/Dec/2018 13:17:54] "GET /lab/14 HTTP/1.1" 301 0
[29/Dec/2018 13:17:54] "GET /lab/14/ HTTP/1.1" 200 1159
Not Found: /
[29/Dec/2018 13:19:32] "GET / HTTP/1.1" 404 2149
[29/Dec/2018 13:19:36] "GET /admin/lab/project/ HTTP/1.1" 200 25342
[29/Dec/2018 13:19:46] "GET /admin/lab/project/33/change/ HTTP/1.1" 200 9786
[29/Dec/2018 13:19:46] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 13:19:50] "GET /admin/lab/project/ HTTP/1.1" 200 25342
[29/Dec/2018 13:20:28] "GET /lab/32 HTTP/1.1" 301 0
[29/Dec/2018 13:20:28] "GET /lab/32/ HTTP/1.1" 200 650
[29/Dec/2018 13:24:31] "GET /lab/ HTTP/1.1" 200 4531
[29/Dec/2018 13:24:32] "GET /lab/11 HTTP/1.1" 301 0
[29/Dec/2018 13:24:32] "GET /lab/11/ HTTP/1.1" 200 32
[29/Dec/2018 13:24:35] "GET /lab/34/ HTTP/1.1" 200 2435
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 11:50:34
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
[29/Dec/2018 13:25:01] "GET /lab/34/ HTTP/1.1" 200 2435
[29/Dec/2018 13:25:13] "GET /lab/34/ HTTP/1.1" 200 2435
[29/Dec/2018 13:25:17] "GET /lab/34/ HTTP/1.1" 200 2435
[29/Dec/2018 13:25:32] "GET /lab/34/ HTTP/1.1" 200 2435
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 13:25:01
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
[29/Dec/2018 13:25:34] "GET /lab/14/ HTTP/1.1" 200 1169
[29/Dec/2018 13:25:38] "GET /lab/34/ HTTP/1.1" 200 2480
[29/Dec/2018 13:26:16] "GET /lab/ HTTP/1.1" 200 4531
[29/Dec/2018 13:26:17] "GET /lab/5/ HTTP/1.1" 200 1274
[29/Dec/2018 13:26:36] "GET /lab/5/ HTTP/1.1" 200 1754
[29/Dec/2018 13:27:12] "GET /lab/5/ HTTP/1.1" 200 1754
[29/Dec/2018 13:27:12] "GET /lab/5/ HTTP/1.1" 200 1307
[29/Dec/2018 13:27:17] "GET /lab/34/ HTTP/1.1" 200 1994
[29/Dec/2018 13:27:50] "GET /lab/ HTTP/1.1" 200 6486
[29/Dec/2018 13:28:19] "GET /lab/8/ HTTP/1.1" 200 1112
[29/Dec/2018 13:28:31] "GET /lab/8/ HTTP/1.1" 200 1112
[29/Dec/2018 13:30:23] "GET /lab/34/ HTTP/1.1" 200 1994
[29/Dec/2018 13:30:28] "GET /lab/33/ HTTP/1.1" 200 7377
[29/Dec/2018 13:30:53] "GET /lab/4/ HTTP/1.1" 200 480
[29/Dec/2018 13:32:26] "GET /admin/lab/ HTTP/1.1" 200 2576
[29/Dec/2018 13:32:26] "GET /admin/ HTTP/1.1" 200 6948
[29/Dec/2018 13:32:30] "GET /admin/paper/paper/ HTTP/1.1" 200 5928
[29/Dec/2018 13:32:30] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 13:32:34] "GET /admin/paper/paper/1/change/ HTTP/1.1" 200 7925
[29/Dec/2018 13:32:34] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 13:32:35] "GET /admin/paper/paper/ HTTP/1.1" 200 5928
[29/Dec/2018 13:32:37] "GET /admin/paper/paper/1/change/ HTTP/1.1" 200 7925
[29/Dec/2018 13:32:37] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 13:32:45] "GET /admin/paper/paper/ HTTP/1.1" 200 5928
[29/Dec/2018 13:32:46] "GET /admin/ HTTP/1.1" 200 6948
[29/Dec/2018 13:34:44] "GET /lab/ HTTP/1.1" 200 6486
[29/Dec/2018 13:35:59] "GET /lab/3/ HTTP/1.1" 200 754
Internal Server Error: /lab/3/
Traceback (most recent call last):
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/SGRNJ/Database/develop/lab/lab/views.py", line 22, in sample_lists
    return render(request,'lab/sample_lists.html',{'samples':samples,'project':project})
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'bootstrap3' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
i18n
l10n
log
static
staticfiles
tz
[29/Dec/2018 13:50:08] "GET /lab/3/ HTTP/1.1" 500 117237
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 13:25:33
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
[29/Dec/2018 13:51:04] "GET /lab/ HTTP/1.1" 200 6486
[29/Dec/2018 13:51:06] "GET /lab/1/ HTTP/1.1" 200 306
[29/Dec/2018 13:51:19] "GET /lab/1/ HTTP/1.1" 200 306
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 13:51:02
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
[29/Dec/2018 13:51:27] "GET /lab/34/ HTTP/1.1" 200 2205
[29/Dec/2018 14:01:56] "GET /lab/34/ HTTP/1.1" 200 2205
Internal Server Error: /lab/
Traceback (most recent call last):
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/SGRNJ/Database/develop/lab/lab/views.py", line 13, in display
    return render(request,'lab/display.html',{'projects':projects})
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/backends/django.py", line 68, in render
    reraise(exc, self.backend)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/backends/django.py", line 89, in reraise
    six.reraise(exc.__class__, new, sys.exc_info()[2])
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/template/engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
TemplateDoesNotExist: base.html
[29/Dec/2018 14:02:00] "GET /lab/ HTTP/1.1" 500 145148
[29/Dec/2018 14:04:11] "GET /lab/ HTTP/1.1" 200 836
[29/Dec/2018 14:04:35] "GET /admin/ HTTP/1.1" 200 6948
[29/Dec/2018 14:04:50] "GET /admin/ HTTP/1.1" 200 6948
Not Found: /
[29/Dec/2018 14:04:52] "GET / HTTP/1.1" 404 2149
[29/Dec/2018 14:04:56] "GET /admin/ HTTP/1.1" 200 6948
Not Found: /alab
[29/Dec/2018 14:04:57] "GET /alab HTTP/1.1" 404 2179
[29/Dec/2018 14:05:00] "GET /lab/ HTTP/1.1" 200 6487
[29/Dec/2018 14:05:11] "GET /lab/1/ HTTP/1.1" 200 306
[29/Dec/2018 14:05:14] "GET /lab/2/ HTTP/1.1" 200 886
[29/Dec/2018 14:05:21] "GET /lab/1/ HTTP/1.1" 200 306
[29/Dec/2018 14:09:18] "GET /lab/ HTTP/1.1" 200 6559
[29/Dec/2018 14:09:18] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 404 1707
[29/Dec/2018 14:09:20] "GET /lab/ HTTP/1.1" 200 6559
[29/Dec/2018 14:09:20] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 404 1707
[29/Dec/2018 14:09:23] "GET /lab/ HTTP/1.1" 200 6559
[29/Dec/2018 14:09:23] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 404 1707
[29/Dec/2018 14:10:25] "GET /lab/ HTTP/1.1" 200 6559
[29/Dec/2018 14:10:25] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 404 1707
[29/Dec/2018 14:10:47] "GET /lab/ HTTP/1.1" 200 7365
[29/Dec/2018 14:10:47] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 404 1707
[29/Dec/2018 14:11:13] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 404 1707
Not Found: /static
[29/Dec/2018 14:11:35] "GET /static HTTP/1.1" 404 2185
[29/Dec/2018 14:12:39] "GET /admin/ HTTP/1.1" 200 6948
Not Found: /favicon.ico
[29/Dec/2018 14:12:39] "GET /favicon.ico HTTP/1.1" 404 2200
[29/Dec/2018 14:12:41] "GET /lab/ HTTP/1.1" 200 7365
[29/Dec/2018 14:12:41] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 404 1707
[29/Dec/2018 14:12:46] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 404 1707
[29/Dec/2018 14:12:52] "GET /lab/ HTTP/1.1" 200 7365
[29/Dec/2018 14:12:53] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 404 1707
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 13:51:25
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
[29/Dec/2018 14:15:08] "GET /lab/ HTTP/1.1" 200 7365
[29/Dec/2018 14:15:08] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 404 1707
[29/Dec/2018 14:15:14] "GET /lab/ HTTP/1.1" 200 7365
[29/Dec/2018 14:15:14] "GET /lab/ HTTP/1.1" 200 7365
[29/Dec/2018 14:15:14] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 404 1707
[29/Dec/2018 14:15:15] "GET /lab/1/ HTTP/1.1" 200 96
[29/Dec/2018 14:15:25] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 404 1707
[29/Dec/2018 14:18:28] "GET /lab/2/ HTTP/1.1" 200 676
[29/Dec/2018 14:18:39] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 404 1707
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 14:15:03
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
[29/Dec/2018 14:24:18] "GET /lab/ HTTP/1.1" 200 7365
Traceback (most recent call last):
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 64, in __call__
    return super(StaticFilesHandler, self).__call__(environ, start_response)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 54, in get_response
    return self.serve(request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 47, in serve
    return serve(request, self.file_path(request.path), insecure=True)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/views.py", line 34, in serve
    absolute_path = finders.find(normalized_path)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 249, in find
    for finder in get_finders():
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 264, in get_finders
    yield get_finder(finder_path)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 277, in get_finder
    return Finder()
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 57, in __init__
    "Your STATICFILES_DIRS setting is not a tuple or list; "
ImproperlyConfigured: Your STATICFILES_DIRS setting is not a tuple or list; perhaps you forgot a trailing comma?
[29/Dec/2018 14:24:18] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 64, in __call__
    return super(StaticFilesHandler, self).__call__(environ, start_response)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 54, in get_response
    return self.serve(request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 47, in serve
    return serve(request, self.file_path(request.path), insecure=True)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/views.py", line 34, in serve
    absolute_path = finders.find(normalized_path)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 249, in find
    for finder in get_finders():
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 264, in get_finders
    yield get_finder(finder_path)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 277, in get_finder
    return Finder()
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 57, in __init__
    "Your STATICFILES_DIRS setting is not a tuple or list; "
ImproperlyConfigured: Your STATICFILES_DIRS setting is not a tuple or list; perhaps you forgot a trailing comma?
[29/Dec/2018 14:24:21] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 500 59
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 14:23:50
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
[29/Dec/2018 14:24:57] "GET /lab/ HTTP/1.1" 200 7365
Traceback (most recent call last):
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 64, in __call__
    return super(StaticFilesHandler, self).__call__(environ, start_response)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 54, in get_response
    return self.serve(request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 47, in serve
    return serve(request, self.file_path(request.path), insecure=True)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/views.py", line 34, in serve
    absolute_path = finders.find(normalized_path)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 249, in find
    for finder in get_finders():
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 264, in get_finders
    yield get_finder(finder_path)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 277, in get_finder
    return Finder()
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 57, in __init__
    "Your STATICFILES_DIRS setting is not a tuple or list; "
ImproperlyConfigured: Your STATICFILES_DIRS setting is not a tuple or list; perhaps you forgot a trailing comma?
[29/Dec/2018 14:24:57] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 64, in __call__
    return super(StaticFilesHandler, self).__call__(environ, start_response)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 54, in get_response
    return self.serve(request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 47, in serve
    return serve(request, self.file_path(request.path), insecure=True)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/views.py", line 34, in serve
    absolute_path = finders.find(normalized_path)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 249, in find
    for finder in get_finders():
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 264, in get_finders
    yield get_finder(finder_path)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 277, in get_finder
    return Finder()
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 57, in __init__
    "Your STATICFILES_DIRS setting is not a tuple or list; "
ImproperlyConfigured: Your STATICFILES_DIRS setting is not a tuple or list; perhaps you forgot a trailing comma?
[29/Dec/2018 14:25:02] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 500 59
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 14:24:28
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
[29/Dec/2018 14:27:46] "GET /lab/ HTTP/1.1" 200 7365
[29/Dec/2018 14:27:46] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 200 121200
[29/Dec/2018 14:27:50] "GET /lab/ HTTP/1.1" 200 7365
[29/Dec/2018 14:27:58] "GET /lab/1/ HTTP/1.1" 200 96
[29/Dec/2018 14:28:11] "GET /lab/8/ HTTP/1.1" 200 1113
[29/Dec/2018 14:28:18] "GET /lab/26 HTTP/1.1" 301 0
[29/Dec/2018 14:28:18] "GET /lab/26/ HTTP/1.1" 200 419
[29/Dec/2018 14:28:52] "GET /lab/ HTTP/1.1" 200 7855
[29/Dec/2018 14:29:43] "GET /lab/ HTTP/1.1" 200 11215
[29/Dec/2018 14:29:43] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[29/Dec/2018 14:30:15] "GET /lab/ HTTP/1.1" 200 11215
[29/Dec/2018 14:30:16] "GET /lab/ HTTP/1.1" 200 6007
[29/Dec/2018 14:30:26] "GET /lab/1/ HTTP/1.1" 200 96
[29/Dec/2018 14:30:28] "GET /lab/2/ HTTP/1.1" 200 676
[29/Dec/2018 14:30:46] "GET /lab/28 HTTP/1.1" 301 0
[29/Dec/2018 14:30:46] "GET /lab/28/ HTTP/1.1" 200 705
[29/Dec/2018 14:30:54] "GET /lab/8/ HTTP/1.1" 200 1113
[29/Dec/2018 14:32:11] "GET /lab/ HTTP/1.1" 200 6007
[29/Dec/2018 14:32:11] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[29/Dec/2018 14:32:12] "GET /lab/1/ HTTP/1.1" 200 283
[29/Dec/2018 14:32:16] "GET /lab/2/ HTTP/1.1" 200 1055
[29/Dec/2018 14:32:21] "GET /lab/9/ HTTP/1.1" 200 1067
[29/Dec/2018 14:32:37] "GET /lab/9/ HTTP/1.1" 200 1067
[29/Dec/2018 14:32:58] "GET /lab/8/ HTTP/1.1" 200 1540
[29/Dec/2018 14:35:17] "GET /lab/ HTTP/1.1" 200 6007
[29/Dec/2018 14:35:17] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[29/Dec/2018 14:35:18] "GET /lab/ HTTP/1.1" 200 6007
[29/Dec/2018 14:35:23] "GET /lab/1/ HTTP/1.1" 200 425
[29/Dec/2018 14:35:49] "GET /lab/ HTTP/1.1" 200 6007
[29/Dec/2018 14:35:50] "GET /lab/1/ HTTP/1.1" 200 454
[29/Dec/2018 14:35:53] "GET /lab/5/ HTTP/1.1" 200 2258
[29/Dec/2018 14:35:57] "GET /lab/9/ HTTP/1.1" 200 1419
[29/Dec/2018 14:36:02] "GET /lab/6/ HTTP/1.1" 200 1208
[29/Dec/2018 14:36:12] "GET /lab/2/ HTTP/1.1" 200 1406
[29/Dec/2018 14:37:42] "GET /lab/ HTTP/1.1" 200 7202
[29/Dec/2018 14:38:31] "GET /lab/8/ HTTP/1.1" 200 1994
[29/Dec/2018 14:38:31] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[29/Dec/2018 14:40:53] "GET /lab/ HTTP/1.1" 200 7130
[29/Dec/2018 14:40:56] "GET /media/SGRNJ/RandD/RD2018013/RD2018013_JHB_CF_report/RD2018013_JHB_CF_report.html HTTP/1.1" 200 3651345
[29/Dec/2018 14:40:56] "GET /media/SGRNJ/RandD/RD2018013/RD2018013_JHB_CF_report/src/0.QC/HMF7_Region.svg HTTP/1.1" 200 79095
[29/Dec/2018 14:40:56] "GET /media/SGRNJ/RandD/RD2018013/RD2018013_JHB_CF_report/src/0.QC/HMF7_UMIcounts.svg HTTP/1.1" 200 155080
[29/Dec/2018 14:40:56] "GET /media/SGRNJ/RandD/RD2018013/RD2018013_JHB_CF_report/src/0.QC/HMF7_downsampleSaturation.svg HTTP/1.1" 200 71150
[29/Dec/2018 14:40:56] "GET /media/SGRNJ/RandD/RD2018013/RD2018013_JHB_CF_report/src/0.QC/FastQC_HMFR2.clean.png HTTP/1.1" 200 109261
[29/Dec/2018 14:40:56] "GET /media/SGRNJ/RandD/RD2018013/RD2018013_JHB_CF_report/src/0.QC/HMF7_downsampleMedianGenes.svg HTTP/1.1" 200 70021
[29/Dec/2018 14:40:56] "GET /media/SGRNJ/RandD/RD2018013/RD2018013_JHB_CF_report/src/0.QC/FastQC_HMFR2.raw.png HTTP/1.1" 200 122631
[29/Dec/2018 14:40:56] "GET /media/SGRNJ/RandD/RD2018013/RD2018013_JHB_CF_report/src/0.QC/HMF7.biotype_pct.svg HTTP/1.1" 200 131281
[29/Dec/2018 14:40:57] "GET /media/SGRNJ/RandD/RD2018013/RD2018013_JHB_CF_report/src/1.QC_mito/HMF7.Mitopercent.png HTTP/1.1" 200 30057
[29/Dec/2018 14:40:57] "GET /media/SGRNJ/RandD/RD2018013/RD2018013_JHB_CF_report/src/2.Cluster/HMF7.corrplot.png HTTP/1.1" 200 17537
[29/Dec/2018 14:40:57] "GET /media/SGRNJ/RandD/RD2018013/RD2018013_JHB_CF_report/src/2.Cluster/HMF7.PercentPerCell.png HTTP/1.1" 200 16335
[29/Dec/2018 14:40:57] "GET /media/SGRNJ/RandD/RD2018013/RD2018013_JHB_CF_report/src/1.QC_mito/HMF7.QC_umapFeatureplot.svg HTTP/1.1" 200 528534
[29/Dec/2018 14:40:57] "GET /media/SGRNJ/RandD/RD2018013/RD2018013_JHB_CF_report/src/3.RD/HMF7.PCA.png HTTP/1.1" 200 17522
[29/Dec/2018 14:40:57] "GET /media/SGRNJ/RandD/RD2018013/RD2018013_JHB_CF_report/src/3.RD/HMF7.PCElbowPlot.png HTTP/1.1" 200 11151
[29/Dec/2018 14:40:57] "GET /media/SGRNJ/RandD/RD2018013/RD2018013_JHB_CF_report/src/3.RD/HMF7.tsne.png HTTP/1.1" 200 48876
[29/Dec/2018 14:40:57] "GET /media/SGRNJ/RandD/RD2018013/RD2018013_JHB_CF_report/src/3.RD/HMF7.umap.png HTTP/1.1" 200 24160
[29/Dec/2018 14:40:57] "GET /media/SGRNJ/RandD/RD2018013/RD2018013_JHB_CF_report/src/1.QC_mito/HMF7.QC_tsneFeatureplot.svg HTTP/1.1" 200 540296
[29/Dec/2018 14:41:05] "GET /lab/25 HTTP/1.1" 301 0
[29/Dec/2018 14:41:05] "GET /lab/25/ HTTP/1.1" 200 876
[29/Dec/2018 14:41:22] "GET /lab/8/ HTTP/1.1" 200 1994
[29/Dec/2018 14:41:55] "GET /lab/22/ HTTP/1.1" 200 485
[29/Dec/2018 14:41:55] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[29/Dec/2018 14:42:01] "GET /lab/27/ HTTP/1.1" 200 3870
[29/Dec/2018 14:42:20] "GET /lab/13 HTTP/1.1" 301 0
[29/Dec/2018 14:42:20] "GET /lab/13/ HTTP/1.1" 200 2008
[29/Dec/2018 14:42:43] "GET /lab/4/ HTTP/1.1" 200 1025
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/P2018008.report.html HTTP/1.1" 200 4585140
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/0.QC/LCP01_Region.svg HTTP/1.1" 200 80643
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/0.QC/LCP01_UMIcounts.svg HTTP/1.1" 200 135783
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/0.QC/LCP01.biotype_pct.svg HTTP/1.1" 200 123896
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/0.QC/LCP01_downsampleMedianGenes.svg HTTP/1.1" 200 75260
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/0.QC/LCP01_downsampleSaturation.svg HTTP/1.1" 200 73825
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/0.QC/FastQC_LCP02.raw.png HTTP/1.1" 200 139322
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/0.QC/FastQC_LCP02.clean.png HTTP/1.1" 200 120117
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/1.QC_mito/LCP01.Mitopercent.png HTTP/1.1" 200 29931
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/2.Cluster/LCP01.PercentPerCell.png HTTP/1.1" 200 16605
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/1.QC_mito/LCP01.QC_tsneFeatureplot.svg HTTP/1.1" 200 499702
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/2.Cluster/LCP01.corrplot.png HTTP/1.1" 200 18374
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/1.QC_mito/LCP01.QC_umapFeatureplot.svg HTTP/1.1" 200 501745
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/3.RD/LCP01.PCElbowPlot.png HTTP/1.1" 200 10597
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/3.RD/LCP01.PCA.png HTTP/1.1" 200 31402
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/3.RD/LCP01.tsne.png HTTP/1.1" 200 42623
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/3.RD/LCP01.umap.png HTTP/1.1" 200 29260
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/7.monocle/LCP01.trajectories_cluster.png HTTP/1.1" 200 24640
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/5.Marker_Gene/LCP01.markergene_DOHeatmapplot.png HTTP/1.1" 200 19684
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/7.monocle/LCP01.Pseudotime_cluster.png HTTP/1.1" 200 27716
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/5.Marker_Gene/LCP01.cluster_Heatmapplot.png HTTP/1.1" 200 12009
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/5.Marker_Gene/LCP01.markergene_Dotplot.png HTTP/1.1" 200 22664
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/5.Marker_Gene/LCP01.markergene_vlnplot1.png HTTP/1.1" 200 28539
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/5.Marker_Gene/LCP01.top10markergene_DOHeatmapplot.png HTTP/1.1" 200 50355
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/5.Marker_Gene/LCP01.markergene_umapFeatureplot1.png HTTP/1.1" 200 35666
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/5.Marker_Gene/LCP01.markergene_tsneFeatureplot1.png HTTP/1.1" 200 48455
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/6.enrich/LCP01_cluster1_GObar.svg HTTP/1.1" 200 193856
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/6.enrich/LCP01_cluster1_KEGGbar.svg HTTP/1.1" 200 155123
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/6.enrich/LCP01_cluster1_Reactomedot.svg HTTP/1.1" 200 183696
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/6.enrich/LCP01_cluster1_Reactomebar.svg HTTP/1.1" 200 162623
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/6.enrich/LCP01_cluster1_GOdot.svg HTTP/1.1" 200 192740
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/6.enrich/LCP01_cluster1_KEGGdot.svg HTTP/1.1" 200 172652
[29/Dec/2018 14:42:52] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/6.enrich/hsa00190_pathway.png HTTP/1.1" 200 105741
[29/Dec/2018 14:42:53] "GET /media/SGRNJ/PROJ1/P2018008/P2018008_report/src/2.Cluster/LCP01.Hcluster.svg HTTP/1.1" 200 2610758
[29/Dec/2018 14:43:48] "GET /lab/1/ HTTP/1.1" 200 454
[29/Dec/2018 14:43:52] "GET /lab/8/ HTTP/1.1" 200 1994
[29/Dec/2018 14:44:09] "GET /lab/26/ HTTP/1.1" 200 997
[29/Dec/2018 14:51:04] "GET /lab/1/ HTTP/1.1" 200 454
[29/Dec/2018 14:51:04] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[29/Dec/2018 14:51:10] "GET /lab/8/ HTTP/1.1" 200 1994
[29/Dec/2018 14:52:09] "GET /lab/8/ HTTP/1.1" 200 1994
[29/Dec/2018 14:52:20] "GET /lab/5/ HTTP/1.1" 200 2258
[29/Dec/2018 14:53:14] "GET /lab/5/ HTTP/1.1" 200 2258
[29/Dec/2018 14:53:16] "GET /lab/ HTTP/1.1" 200 7971
[29/Dec/2018 14:53:22] "GET /lab/5/ HTTP/1.1" 200 2258
[29/Dec/2018 14:53:26] "GET /lab/33/ HTTP/1.1" 200 12279
[29/Dec/2018 14:53:37] "GET /lab/21 HTTP/1.1" 301 0
[29/Dec/2018 14:53:37] "GET /lab/21/ HTTP/1.1" 200 421
[29/Dec/2018 14:53:40] "GET /lab/13/ HTTP/1.1" 200 2008
[29/Dec/2018 14:53:44] "GET /lab/2/ HTTP/1.1" 200 1406
[29/Dec/2018 14:53:47] "GET /lab/7/ HTTP/1.1" 200 1500
[29/Dec/2018 14:53:51] "GET /lab/34/ HTTP/1.1" 200 3452
[29/Dec/2018 14:53:54] "GET /lab/32/ HTTP/1.1" 200 1230
[29/Dec/2018 14:54:05] "GET /admin/ HTTP/1.1" 200 6948
[29/Dec/2018 14:54:05] "GET /admin/ HTTP/1.1" 200 6948
[29/Dec/2018 14:54:08] "GET /admin/lab/sample/ HTTP/1.1" 200 64036
[29/Dec/2018 14:54:08] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 14:54:14] "GET /admin/lab/sample/?p=1 HTTP/1.1" 200 66756
[29/Dec/2018 14:54:14] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
Not Found: /
[29/Dec/2018 14:54:22] "GET / HTTP/1.1" 404 2149
[29/Dec/2018 14:54:29] "GET /lab/ HTTP/1.1" 200 7971
[29/Dec/2018 14:54:43] "GET /lab/12 HTTP/1.1" 301 0
[29/Dec/2018 14:54:43] "GET /lab/12/ HTTP/1.1" 200 2352
[29/Dec/2018 14:54:57] "GET /lab/12/ HTTP/1.1" 200 2412
[29/Dec/2018 14:56:22] "GET /lab/12/ HTTP/1.1" 200 3520
[29/Dec/2018 14:56:22] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[29/Dec/2018 14:57:02] "GET /lab/12/ HTTP/1.1" 200 3520
[29/Dec/2018 14:57:03] "GET /lab/12/ HTTP/1.1" 200 3812
[29/Dec/2018 14:57:06] "GET /lab/5/ HTTP/1.1" 200 3731
[29/Dec/2018 14:57:11] "GET /lab/32/ HTTP/1.1" 200 2124
[29/Dec/2018 14:57:32] "GET /lab/1/ HTTP/1.1" 200 583
[29/Dec/2018 14:59:03] "GET /lab/ HTTP/1.1" 200 7971
[29/Dec/2018 14:59:04] "GET /lab/1/ HTTP/1.1" 200 714
[29/Dec/2018 14:59:07] "GET /lab/6/ HTTP/1.1" 200 2065
[29/Dec/2018 14:59:25] "GET /lab/6/ HTTP/1.1" 200 2065
[29/Dec/2018 14:59:26] "GET /lab/6/ HTTP/1.1" 200 2068
[29/Dec/2018 14:59:58] "GET /lab/27/ HTTP/1.1" 200 6842
[29/Dec/2018 15:00:02] "GET /lab/32/ HTTP/1.1" 200 2258
[29/Dec/2018 15:00:27] "GET /lab/8/ HTTP/1.1" 200 3416
[29/Dec/2018 15:00:37] "GET /lab/8/ HTTP/1.1" 200 3416
[29/Dec/2018 15:00:54] "GET /lab/8/ HTTP/1.1" 200 3416
[29/Dec/2018 15:00:56] "GET /lab/5/ HTTP/1.1" 200 3866
[29/Dec/2018 15:01:32] "GET /lab/1/ HTTP/1.1" 200 717
[29/Dec/2018 15:01:32] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[29/Dec/2018 15:03:14] "GET /lab/1/ HTTP/1.1" 200 717
[29/Dec/2018 15:03:18] "GET /lab/1/ HTTP/1.1" 200 717
[29/Dec/2018 15:04:05] "GET /lab/8/ HTTP/1.1" 200 3416
[29/Dec/2018 15:05:26] "GET /lab/8/ HTTP/1.1" 200 3430
[29/Dec/2018 15:05:35] "GET /lab/1/ HTTP/1.1" 200 731
[29/Dec/2018 15:06:25] "GET /lab/1/ HTTP/1.1" 200 747
[29/Dec/2018 15:06:29] "GET /lab/6/ HTTP/1.1" 200 2098
[29/Dec/2018 15:06:35] "GET /lab/5/ HTTP/1.1" 200 3896
[29/Dec/2018 15:07:15] "GET /lab/5/ HTTP/1.1" 200 4186
[29/Dec/2018 15:07:15] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[29/Dec/2018 15:07:33] "GET /lab/29/ HTTP/1.1" 200 2444
[29/Dec/2018 15:07:46] "GET /lab/29/ HTTP/1.1" 200 2444
[29/Dec/2018 15:08:14] "GET /lab/33/ HTTP/1.1" 200 24615
[29/Dec/2018 15:09:54] "GET /lab/33/ HTTP/1.1" 200 24615
[29/Dec/2018 15:10:01] "GET /lab/27/ HTTP/1.1" 200 7404
[29/Dec/2018 15:19:46] "GET /lab/1/ HTTP/1.1" 200 773
[29/Dec/2018 15:19:46] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[29/Dec/2018 15:19:50] "GET /lab/8/ HTTP/1.1" 200 3692
[29/Dec/2018 15:19:54] "GET /lab/2/ HTTP/1.1" 200 2761
[29/Dec/2018 15:20:22] "GET /lab/2/ HTTP/1.1" 200 2761
[29/Dec/2018 15:20:43] "GET /lab/1/ HTTP/1.1" 200 773
[29/Dec/2018 15:21:17] "GET /lab/1/ HTTP/1.1" 200 763
[29/Dec/2018 15:21:32] "GET /lab/1/ HTTP/1.1" 200 0
[29/Dec/2018 15:21:35] "GET /lab/1/ HTTP/1.1" 200 743
[29/Dec/2018 15:21:36] "GET /lab/1/ HTTP/1.1" 200 743
[29/Dec/2018 15:21:37] "GET /lab/1/ HTTP/1.1" 200 743
[29/Dec/2018 15:21:38] "GET /lab/2/ HTTP/1.1" 200 2731
[29/Dec/2018 15:23:16] "GET /lab/2/ HTTP/1.1" 200 2741
[29/Dec/2018 15:23:34] "GET /lab/3/ HTTP/1.1" 200 3056
[29/Dec/2018 15:23:41] "GET /lab/22/ HTTP/1.1" 200 784
[29/Dec/2018 15:24:02] "GET /lab/ HTTP/1.1" 200 7985
[29/Dec/2018 15:24:03] "GET /lab/23 HTTP/1.1" 301 0
[29/Dec/2018 15:24:03] "GET /lab/23/ HTTP/1.1" 200 787
[29/Dec/2018 15:24:03] "GET /lab/23/ HTTP/1.1" 200 787
[29/Dec/2018 15:24:06] "GET /lab/29/ HTTP/1.1" 200 2451
[29/Dec/2018 15:25:03] "GET /lab/3/ HTTP/1.1" 200 3083
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 14:27:45
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function wrapper at 0x7fe62aec3140>
Performing system checks...

Traceback (most recent call last):
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/SGRNJ/Database/develop/lab/lab_project/urls.py", line 25, in <module>
    url(r'^$', main_site),
NameError: name 'main_site' is not defined
[29/Dec/2018 15:31:24] "GET /lab/ HTTP/1.1" 200 7985
[29/Dec/2018 15:31:24] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
Internal Server Error: /
Traceback (most recent call last):
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/SGRNJ/Database/develop/lab/lab/views.py", line 9, in main_site
    return redirect("/lab")
NameError: global name 'redirect' is not defined
[29/Dec/2018 15:31:25] "GET / HTTP/1.1" 500 65661
Performing system checks...

System check identified no issues (0 silenced).
December 29, 2018 - 15:31:21
Django version 1.11.10, using settings 'lab_project.settings'
Starting development server at http://0:88/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function wrapper at 0x7fe47a877140>
Performing system checks...

Traceback (most recent call last):
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Public/Software/conda/miniconda/envs/django1.11/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/SGRNJ/Database/develop/lab/lab_project/urls.py", line 19, in <module>
    from lab.views import *
  File "/SGRNJ/Database/develop/lab/lab/views.py", line 5, in <module>
    from django.http import HttpResponse,redirect
ImportError: cannot import name redirect
[29/Dec/2018 15:33:15] "GET /admin/ HTTP/1.1" 200 6948
[29/Dec/2018 15:33:18] "GET / HTTP/1.1" 302 0
[29/Dec/2018 15:33:18] "GET /lab/ HTTP/1.1" 200 7985
[29/Dec/2018 15:33:22] "GET /admin/ HTTP/1.1" 200 6948
[29/Dec/2018 15:33:23] "GET /admin/ HTTP/1.1" 200 6948
[29/Dec/2018 15:33:25] "GET / HTTP/1.1" 302 0
[29/Dec/2018 15:33:25] "GET /lab/ HTTP/1.1" 200 7985
[29/Dec/2018 15:33:29] "GET /admin/ HTTP/1.1" 200 6948
[29/Dec/2018 15:33:31] "GET / HTTP/1.1" 302 0
[29/Dec/2018 15:33:32] "GET /lab/ HTTP/1.1" 200 7985
[29/Dec/2018 15:33:39] "GET /lab/1/ HTTP/1.1" 200 780
[29/Dec/2018 15:33:43] "GET /lab/3/ HTTP/1.1" 200 3083
[29/Dec/2018 15:33:50] "GET /lab/32/ HTTP/1.1" 200 2453
[29/Dec/2018 15:34:15] "GET /lab/33/ HTTP/1.1" 200 24622
[29/Dec/2018 15:34:48] "GET /admin/ HTTP/1.1" 200 6948
[29/Dec/2018 15:34:51] "GET / HTTP/1.1" 302 0
[29/Dec/2018 15:34:51] "GET /lab/ HTTP/1.1" 200 7985
[29/Dec/2018 15:34:53] "GET /admin/ HTTP/1.1" 200 6948
[29/Dec/2018 15:34:55] "GET / HTTP/1.1" 302 0
[29/Dec/2018 15:34:56] "GET /lab/ HTTP/1.1" 200 7985
[29/Dec/2018 15:34:57] "GET /lab/8/ HTTP/1.1" 200 3699
[29/Dec/2018 15:35:22] "GET /admin/ HTTP/1.1" 200 6948
[29/Dec/2018 15:35:24] "GET / HTTP/1.1" 302 0
[29/Dec/2018 15:35:24] "GET /lab/ HTTP/1.1" 200 7985
[29/Dec/2018 15:35:26] "GET /admin/ HTTP/1.1" 200 6948
[29/Dec/2018 15:35:29] "GET /admin/paper/paper/ HTTP/1.1" 200 5928
[29/Dec/2018 15:35:29] "GET /admin/jsi18n/ HTTP/1.1" 200 7758
[29/Dec/2018 15:35:35] "GET /admin/ HTTP/1.1" 200 6948
[29/Dec/2018 15:36:06] "GET /admin/logout/ HTTP/1.1" 200 1019
[29/Dec/2018 15:36:08] "GET / HTTP/1.1" 302 0
[29/Dec/2018 15:36:09] "GET /lab/ HTTP/1.1" 200 7985
[29/Dec/2018 15:36:11] "GET /admin/logout/ HTTP/1.1" 302 0
[29/Dec/2018 15:36:11] "GET /admin/ HTTP/1.1" 302 0
[29/Dec/2018 15:36:11] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1660
[29/Dec/2018 15:36:13] "GET / HTTP/1.1" 302 0
[29/Dec/2018 15:36:13] "GET /lab/ HTTP/1.1" 200 7985
[29/Dec/2018 15:38:42] "GET /lab/29/ HTTP/1.1" 200 2451
